### ISSUE TITLE
Game crashes when entering the front train car first time

### ISSUE THREAD

**Issue by ruinedplay** [IntelOrca/biorand#495] opened 2023-07-14 15:32 UTC
### Version

3.0.9 (4d8d5d6)

### Seed

R730-4Y14-XXQA602Z2QF00L82XAH0ZBU7U5EZGXZZPGW

### Scenario

RE 3 (Jill)

### Player Character

Jake

### What happened?

Game crashes when entering the front train car for the first time from the back train car. The door texture glitches during the door transition and the game crash either at the end of the transition or the start of the cutscene,

**Comment by IntelOrca** [comment] 2023-12-16 12:29
Duplicate of #352

**Closed by IntelOrca** 2023-12-16 12:29 UTC
Labels: RE 3
