### ISSUE TITLE
Another Transition Crash

### ISSUE THREAD

**Issue by PlantBrain** [IntelOrca/biorand#479] opened 2023-07-04 13:17 UTC
### Version

3.0.8 (a1e8985)

### Seed

R721-9HWU-TEZWH0BZ9U000KRZ3ZZZEE5WF1EGCRZZK2Y

### Scenario

RE 2 (Claire A)

### Player Character

Claire (RE2)

### What happened?

The game crashed moving from 410 (Alligator Pool) to 409 (Bridge 2f). I disabled random NPCs and I was able to progress without it crashing.

[Claire A_04_2023-07-04 14^14.17.zip](https://github.com/IntelOrca/biorand/files/11949668/Claire.A_04_2023-07-04.14.14.17.zip)

**Comment by Neil-F2** [comment] 2023-07-04 14:59
I can confirm this crash, disabling NPCs worked too

**Comment by IntelOrca** [comment] 2023-07-04 20:52
Duplicate of #470

**Closed by IntelOrca** 2023-07-04 20:52 UTC
