### ISSUE TITLE
Leon B Lab Elevator Crash

### ISSUE THREAD

**Issue by PlantBrain** [IntelOrca/biorand#770] opened 2024-01-04 15:42 UTC
### Version

3.2.0 (c468b41)

### Seed

R721-TZHN-XEVH30A6Z9R0002J0JW9C7U6XVZYFFBZYUBZYZZ41H1000TZZ

### Scenario

RE 2 (Leon B)

### Player Character

Leon (RE2)

### What happened?

After the self destruct system is activated and you have to go and save Sherry in the security office, the game will crash in room 606 on the door loading screen for the elevator whilst carrying Sherry towards it.

NPC, music, item and enemy rando are active.

I've attached the log and a save before entering the security office.

[Leon B_01_2024-01-04 15^27.56.zip](https://github.com/IntelOrca/biorand/files/13832185/Leon.B_01_2024-01-04.15.27.56.zip)
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/13832174/log_pl0.txt)

**Comment by PlantBrain** [comment] 2024-01-04 16:21
So I disabled each randomised function one by one until I got past and oddly it was the randomised items function that was crashing it.

**Comment by IntelOrca** [comment] 2024-01-04 23:12
Duplicate of #769

**Closed by IntelOrca** 2024-01-04 23:12 UTC
