### ISSUE TITLE
RE2 (v2.1.5) Ada + Magnum = Crash

### ISSUE THREAD

**Issue by NawiEchi** [IntelOrca/biorand#161] opened 2023-01-15 01:46 UTC
R520-5U4A-Z1ZZZQ422001

As soon as I equip the magnum the game crashes

This is probably related to the room 403 Leon-->Ada bug

**Comment by IntelOrca** [comment] 2023-01-15 11:50
In that case it is a duplicate of #158

**Closed by IntelOrca** 2023-01-15 11:50 UTC
