### ISSUE TITLE
Richard Zombie's graphics are broken.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#498] opened 2023-07-22 16:12 UTC
### Version

3.0.9 (1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

Something is wrong with Richard Zombie's clothes.

exp
https://youtu.be/rbEAiEDmjFU?t=1039

**Comment by IntelOrca** [comment] 2023-07-23 20:47
Duplicate of  #501

**Closed by IntelOrca** 2023-07-23 20:47 UTC
Labels: bug, RE 2
