### ISSUE TITLE
Game crashes when going down the ladder to fight G Adult

### ISSUE THREAD

**Issue by AuthenticSky** [IntelOrca/biorand#726] opened 2023-12-23 07:05 UTC
### Version

3.1.8 (2f583cd)

### Seed

R721-R14E-TWZC00G6Z3Z9U02H80W0K004ZZZZZZZZZZZZZZZXZZ0U00XZZ

### Scenario

RE 2 (Claire A)

### Player Character

Jill (RE3R)

### What happened?

Game consistently crashes while going down the ladder to fight G Adult in the Sewer

**Comment by IntelOrca** [comment] 2023-12-29 02:11
Duplicate of  #711

**Closed by IntelOrca** 2023-12-29 02:11 UTC
