### ISSUE TITLE
Biorand ignores William

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#842] opened 2024-02-22 02:41 UTC
### Version

3.2.6 (8171900)

### Seed

R720-QPVM-ZWHH4080WME58H00H3XT6WHM5H40000000000000000Z00F30YZZ

### Scenario

RE 2 (Leon A)

### Player Character

Doesn't matter

### What happened?

I have noticed that William was getting deselected every time i opened the random, so i decided to play only with William as NPCs
![Captura de pantalla (702)](https://github.com/IntelOrca/biorand/assets/130115877/133ef4a4-8235-4bfd-b8fe-c72eec6beb85)
Well, i didn't worked seems like i doesn't recognize William
![Captura de pantalla (703)](https://github.com/IntelOrca/biorand/assets/130115877/598332a2-8e46-401a-bdab-e89d79a8d2dc)
By the way, i loved the Randy Rando

**Comment by otamega72** [comment] 2024-02-22 14:13
I knew this problem when biorand still in v3.2.3 , (issue #802) , 
biorand only can handle first 75 npcs. and randomize music only can handle first 15 music.
By default v3.2.6 re2 pld0 = 52 , pld1 = 25 , total 77 , so last 2 npcs cannot be randomized.
And don't forget to count your customize npcs too (if any) in %appdata%biorand\data

My temporary solution : 
If I want music [reuc] , rename [reuc] to [1reuc] in biorand\data\bgm , make sure the music I want is in first 15.
Same as npc , If I want npc [william] , rename to [1william] in biorand\data\re2\pld0 , and don't forget to rename william voice and hurt folders too.

**Comment by IntelOrca** [comment] 2024-02-22 14:47
Duplicate of #802

**Closed by IntelOrca** 2024-02-22 14:47 UTC
