### ISSUE TITLE
Crash when  entering G-Spawn ladder

### ISSUE THREAD

**Issue by siroco1** [IntelOrca/biorand#215] opened 2023-02-02 20:41 UTC
Version: BioRand 2.1.7
Seed: R521-JLRA-R8Z50GX3300Z

Seed crashed after the Chief Irons death cutscene, right after taking the ladder.

**Comment by IntelOrca** [comment] 2023-03-04 22:54
This might have been caused by sharing enemy IDs with bosses and normal enemies. If this is the case, should be fixed now.

**Closed by IntelOrca** 2023-03-04 22:54 UTC
