### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by LordOfLocation** [IntelOrca/biorand#259] opened 2023-02-20 14:23 UTC
### Version

2.2.2 (81c73fc)

### Seed

R621-TLXB-XN4HHQZ3FL7PTZ3ZZ000000000YZ0HZ

### Scenario

RE 2 (Claire A)

### What happened?

When Lighting the signal Beacon in Room 501, the Game Crashes.

**Comment by IntelOrca** [comment] 2023-02-21 20:03
Duplicate of #251

**Closed by IntelOrca** 2023-02-21 20:03 UTC
