### ISSUE TITLE
Crash, RE3

### ISSUE THREAD

**Issue by STARSMember930** [IntelOrca/biorand#571] opened 2023-09-07 02:55 UTC
### Version

3.1.1 (1e8850a)

### Seed

R730-VLCY-WXHH48LZ9YL00QJZZZZZWZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Claire RE2

### What happened?

Game continuously crashes as you go through the initial cable car sequence. After getting past the gate with the gems, proceed to the cable car. Once you enter, you will have a conversation with Nicholai (RE5 Chris) and interact with Mikhail (also RE5 Chris). When you enter the next room to meet Carlos and Nicholai, the game crashes. Up to this point I have completed the medical office beyond the fire, have completed the Stagla gas station, have not interacted with Mayor Warren's statue (the door is still closed until I go back) and I received all three key items (fuse, power cord, mixed oil). Upon adding 2 of the 3 key items, this crash happens. If you only add 1 of the 3 items or none of the items, it still crashes once you open the door. I have tested this by leaving the fuse in the item box, but it still crashes. If you add all 3 of 3 key items, you get a Carlos cut-scene (feature Annette RE2R), followed by the initial cut scenes; a crash still happens when you enter the next room. I tried to door-skip my way past the error, but the second cable car room (which usually has the wrench) does not show up. If you jump to the _cable car moving_ room you can get around this error but you are unable to finish the areas.

**Comment by otamega72** [comment] 2023-09-07 03:51
Disable mod_biorand\room (rename folder name "room" to room.01) , run the game again. 
If game ok , maybe the problem is some npc crashed the game.

**Comment by IntelOrca** [comment] 2023-09-07 20:43
You are playing an old version. I think this is fixed in the latest version, 3.1.2.

**Closed by IntelOrca** 2023-09-07 20:43 UTC
