### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by OuTKasTx** [IntelOrca/biorand#884] opened 2024-04-20 08:09 UTC
### Version

3.2.6 (8171900)

### Seed

R710-YU6H-XXFE60VZZPEZUHA0H3N9P5KP9HHFQKYGZYVZKVZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Chris (CV)

### What happened?

was heading downstairs from the lab room right outside of the entrance where the box is and when i went into the next room it crashed and said couldnt find file /horr/jpn/24.tmd. whatever that means

**Comment by IntelOrca** [comment] 2024-04-22 17:55
duplicate of #878

**Closed by IntelOrca** 2024-04-22 17:55 UTC
