### ISSUE TITLE
RE3 - Headless Rebecca

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#469] opened 2023-06-29 02:11 UTC
### Version

3.0.8 (a1e8985)

### Seed

R730-0NKK-ZTH00HVZ9Y000Z0HZZZ3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ark

### What happened?

Speaks for itself. 
![image](https://github.com/IntelOrca/biorand/assets/123828971/3f54df9f-934a-428b-a6f9-ff0a34448f79)

**Comment by IntelOrca** [comment] 2023-06-29 07:56
Duplicate of #352

**Closed by IntelOrca** 2023-06-29 07:56 UTC
