### ISSUE TITLE
RE2 - Unable to retrieve Platform Key - Softlock

### ISSUE THREAD

**Issue by YoshiChief** [IntelOrca/biorand#202] opened 2023-01-26 21:20 UTC
Seed: R521-NK8T-ZTHH5C9LL56G
Version: 2.1.7
Scenario: Leon B
Item Required: (PlatformKey x1) in 208:6

Was unable to beat the seed without cheating.

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/10513460/log_pl0.txt)

**Comment by IntelOrca** [comment] 2023-01-26 23:32
Duplicate of #200

**Closed by IntelOrca** 2023-01-26 23:32 UTC
