### ISSUE TITLE
RE 3, room 211, crash after worm right

### ISSUE THREAD

**Issue by Ripperc100jr** [IntelOrca/biorand#283] opened 2023-03-12 23:56 UTC
[Crash.zip](https://github.com/IntelOrca/biorand/files/10952443/Crash.zip)
### Version

3.0.0 (fafcdd5)

### Seed

R730-0000-ZTEE3EUZ9YE00NTKEVP1ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### What happened?

Room 415 entering from room 124, Boss worm fight crash's when climbing to escape. Using both methods of killing him (Acid rounds & the light posts) they both end in the same fashion.

Room 105 entering from room 207 also crash's when trying to view the Brad shooting cutscene (unknown who the NPC is) Able to progress after entering a different room, but still wanted to report it

**Comment by IntelOrca** [comment] 2023-03-16 21:57
The Brad shooting cutscene is fixed.
I am unable to reproduce the crash after the room fight. I think the crash is when entering room 211 (Restaurant), but it must only be if certain flags are set.

**Comment by IntelOrca** [comment] 2023-05-20 14:25
May be fixed in a later version

**Closed by IntelOrca** 2023-05-20 14:25 UTC
Labels: RE 3
