### ISSUE TITLE
Unable to find key item to swap

### ISSUE THREAD

**Issue by BittyMERC** [IntelOrca/biorand#375] opened 2023-05-20 15:38 UTC
### Version

3.0.2 (10d7467)

### Seed

R720-0000-WNHHH0MZ9Y000JA22820ZZZZZZZZZZZZXZZ

### Scenario

RE 2 (Leon A)

### Player Character

Unknown

### What happened?

i didnt get the chance to load in yet. got a popup stating unable to find key item to swap please report this seed and try another.
![key item swap error](https://github.com/IntelOrca/biorand/assets/109184042/46864b2e-e9cd-4c71-8470-5444e677742c)
here is a screenshot of al lsettings incase you need  that as well. also i have every single Randomize NPC's checked 
![biorand settings](https://github.com/IntelOrca/biorand/assets/109184042/eb4be655-fd84-4b0f-bc27-6ac8b8ca8b5c)

**Comment by IntelOrca** [comment] 2023-05-20 16:02
Duplicate of #368

**Closed by IntelOrca** 2023-05-20 16:02 UTC
