### ISSUE TITLE
re1 room 308 crash

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#793] opened 2024-01-17 00:04 UTC
### Version

3.2.3 (5e89e20)

### Seed

R710-ZEW4-XNHH4077Z9Y0403N9KW9K894ZZZVZZZQZZZZZZZZGVFZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Alexia

### What happened?

game crashed when trying to enter room 308. attached a save file at the door. also heres a [screenshot](https://i.imgur.com/1kY4JTk.png) of what popped up when it crashed. 
[Jill_14_2024-01-16 18^18.39.zip](https://github.com/IntelOrca/biorand/files/13956888/Jill_14_2024-01-16.18.18.39.zip)

**Comment by IntelOrca** [comment] 2024-01-22 00:57
This occurs in vanilla as well. Not sure what the issue is, but I know people have had it in various different rooms.

**Comment by IntelOrca** [comment] 2024-01-26 00:22
Duplicate of #808

**Closed by IntelOrca** 2024-01-26 00:22 UTC
Labels: bug, RE 1
