### ISSUE TITLE
Screen freezes during cutscene

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#224] opened 2023-02-06 05:34 UTC
### Version

2.2.1 (bd54d6c)

### Seed

R620-M5H2-ZTLK4C4VF71G0H3000KKC1MAKVYZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

![Screenshot_20230206_122934](https://user-images.githubusercontent.com/122331724/216891455-cdfaf779-097c-4100-9f92-e2e40b4e4086.png)
![Screenshot_20230206_123003](https://user-images.githubusercontent.com/122331724/216891470-22befa3f-9dea-4bf3-92d3-6b87bd44bf3a.png)
When the room loads, the cutscene plays but the screen is frozen. I can hear myself move around but the screen is still froze. when I push F8 then the screen minimizes and then I can see where I've moved but the screen is black and it just has a weird glitch.

**Comment by IntelOrca** [comment] 2023-02-09 21:46
Duplicate of #241

**Closed by IntelOrca** 2023-02-09 21:46 UTC
