### ISSUE TITLE
Invisible Killers, Piers wearing his head as a shirt

### ISSUE THREAD

**Issue by CalAnon** [IntelOrca/biorand#739] opened 2023-12-29 18:26 UTC
### Version

3.1.8 (133fb8e)

### Seed

R721-YQ4B-XXRA00Q6Z2Y7E17X8HW8210CKCV052C9FLA3B4YNQX1E0KZZZ

### Scenario

RE 1 (Chris)

### Player Character

Sheva as Claire

### What happened?

In the 2F Statue Hall (God of Sun/Moon), I've had issues in this and another seed where invisible or out-of-bounds enemies have been able to attack my player character. Also, as a funny, Piers replacing Irons results in Piers wearing his face as a shirt. I mean, I've heard of having an ego, but your own face as a shirt? LOL. But, seriously, the invisible enemies being able to harm you is a problem.
![Piers Shirt Face 1](https://github.com/IntelOrca/biorand/assets/155108879/9254e8c4-91e0-42d1-a0c7-44c42d24a472)
![Uploading Piers Shirt Face 2.png…]()
![Uploading Piers Shirt Face 3.png…]()

**Comment by IntelOrca** [comment] 2023-12-29 18:40
Duplicate of #518 and #734

**Closed by IntelOrca** 2023-12-29 18:40 UTC
