### ISSUE TITLE
Crash After Chief's dialogue

### ISSUE THREAD

**Issue by siroco1** [IntelOrca/biorand#218] opened 2023-02-04 06:12 UTC
Version: BioRand 2.1.7
Seed: R521-5M3G-R8ZC0GX3300Q

My seeds with Claire A keep crashing when entering the stuffed tiger room.

**Comment by IntelOrca** [comment] 2023-02-04 12:08
I can't reproduce this, I generated this seed with 2.1.7 and went through 21B to 10E and back again without it crashing.

**Comment by IntelOrca** [comment] 2023-02-09 00:24
Might be fixed by 954a2884e51c7cc7e539a384477f01de521adebb

**Comment by IntelOrca** [comment] 2023-03-16 21:43
I think this is fixed now

**Closed by IntelOrca** 2023-03-16 21:43 UTC
