### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ripperc100jr** [IntelOrca/biorand#242] opened 2023-02-09 09:20 UTC
### Version

2.2.1 (bd54d6c)

### Seed

R620-FNQ1-ZTJJJMZ9FGEQK49K49ZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

Got to the warehouse door room and going down the elevator crash's the game

**Comment by IntelOrca** [comment] 2023-02-09 21:04
@Ripperc100jr can you give more information about which room and elevator you are referring to?

**Comment by Ripperc100jr** [comment] 2023-02-09 22:53
The room where you open the warehouse door as leon and use the lighter to grab extra supplies. Going down that elevator in that room causes the crash

**Comment by IntelOrca** [comment] 2023-02-10 00:12
Duplicate of #228

**Closed by IntelOrca** 2023-02-10 00:12 UTC
