### ISSUE TITLE
RE 2, room 109, Claire A crash with random enemy placements when shot colt SAA

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#199] opened 2023-01-24 14:06 UTC
Seed: R521-PM18-XMHH07ZLLB7Z
Claire A
random enemy placement : ON
Other things?：Brad Zombie etc... ↓
https://www.youtube.com/shorts/J70KaPMWZ7E

**Comment by IntelOrca** [comment] 2023-12-29 02:41
I think it is a duplicate of  #426

**Closed by IntelOrca** 2023-12-29 02:41 UTC
Labels: glitch, RE 2
