### ISSUE TITLE
Crash when shooting zombie dogs with Assault Rifle.

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#436] opened 2023-06-11 21:08 UTC
### Version

3.0.5 (b953316)

### Seed

R730-C877-XXQHA9LZ9Y700LVPNUP0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Claire

### What happened?

Consistently crashes when shooting zombie dogs with the assault rifle.
Happens in multiple rooms, with full auto or manual shooting.

**Comment by IntelOrca** [comment] 2023-06-15 19:52
Duplicate of #434

**Closed by IntelOrca** 2023-06-15 19:52 UTC
