### ISSUE TITLE
3.0.8 RE3 20b graphics corruption when Mikhail 's killing zombies outside cable car

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#473] opened 2023-07-02 02:21 UTC
### Version

3.0.8

### Seed

R730-U86A-ZTC885XZBYU20QRPW4T03080100K0WZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Nemesis (not in default biorand list)

### What happened?

Connected 20B:0 to 112:1 , 
20B -> 112 -> 20B  , graphics corruption

npc glitch too.
20B:255 (0x3966) [MIKHAIL VIKTOR] becomes [BRAD ZOMBIE (sheva)]
20B:255 (0x39EE) [MIKHAIL VIKTOR] becomes [BRAD ZOMBIE (sheva)]

[g 03_2023-07-02 01^46.01.zip](https://github.com/IntelOrca/biorand/files/11928530/g.03_2023-07-02.01.46.01.zip)

refer :
https://github.com/IntelOrca/biorand/issues/424#issue-1739499167

![20b Capture 3](https://github.com/IntelOrca/biorand/assets/120957601/15e31da1-820b-46a3-aff4-655d7f96521e)
![20b Capture 4](https://github.com/IntelOrca/biorand/assets/120957601/f2dce184-95e1-4103-b0cd-6f038e224a00)
![20b Capture2](https://github.com/IntelOrca/biorand/assets/120957601/e6b4f699-e9a9-4022-bfb8-1a3294008813)
![20b Capture 5](https://github.com/IntelOrca/biorand/assets/120957601/d217b8e2-64d1-4b1c-8662-e07286dcd704)

**Comment by IntelOrca** [comment] 2023-09-15 16:47
Duplicate of #540

**Closed by IntelOrca** 2023-09-15 16:47 UTC
Labels: bug, RE 3
