### ISSUE TITLE
RE 3, room 315, crash due to enemy change

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#598] opened 2023-09-17 09:42 UTC
### Version

3.1.3 (cbe02d7)

### Seed

R730-WU6P-XXNE5ALZ9PN10QQR9W4TWZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Wesker CV (I dont think it matters)

### What happened?

Coming back from the hospital, entering the clock chamber. Where you give the 3 amber, obsidian, crystal. I kept getting a crash.

**Comment by IntelOrca** [comment] 2023-09-17 10:10
@JackDeRipper494 do you have a saved game before the crash happens?

**Comment by spritefun** [comment] 2023-09-29 22:19
Same thing happens to me, I have a save file but the seed is different, ill upload anyway to save time.
[14_2023-09-29 14^26.38.zip](https://github.com/IntelOrca/biorand/files/12772352/14_2023-09-29.14.26.38.zip)

**Comment by IntelOrca** [comment] 2023-09-30 11:42
@spritefun please post the seed as well

**Comment by spritefun** [comment] 2023-09-30 12:48
I realised that save was just before the nemesis fight where Jill gets infected, so I tried playing again to get you a save closer to the end of the hosp and I got two different crashes. I got a crash entering B3 room, and got another one just after leaving the clock tower with carlos, I did manage to get a save just after starting Carlos part of the game though if that helps? If not, let me know and I'll keep trying to get one closer to the end of the hospital section.

[15_2023-09-30 13^41.27.zip](https://github.com/IntelOrca/biorand/files/12774687/15_2023-09-30.13.41.27.zip)

Seed: R730-XK7A-T5HH4HNZLYB10QHR0XAAWZ1ZZZZZZZZZZZZZZZZXZZZZ

**Comment by IntelOrca** [comment] 2023-10-01 23:29
@spritefun 
I think this saved game is too early, I played it, but went all the way to the hospital without any crashes. If possible could you upload a saved game just before the opening the door that causes the crash. Use the debug menu to save anywhere.

**Comment by spritefun** [comment] 2023-10-02 09:34
@IntelOrca 
Got it!!
I had a crash during the hospital, but I feel like that was because of me skipping doors. Anyway I did exactly what I did the first time, went to 4F first, then B3, saved right outside door and got that same crash again.

[14_2023-10-02 10^31.48.zip](https://github.com/IntelOrca/biorand/files/12781490/14_2023-10-02.10.31.48.zip)

**Comment by IntelOrca** [comment] 2023-10-03 08:27
@spritefun thanks, I'll investigate this later

**Comment by IntelOrca** [comment] 2023-10-06 23:27
@spritefun I was able to reproduce the issue from your saved game and have now fixed it. Thanks!

**Closed** 2023-10-06 23:27 UTC
Labels: bug, RE 3

**Comment by spritefun** [comment] 2023-10-07 08:13
Awesome, thanks!!
