### ISSUE TITLE
RE3 Cutscene don't have any dialogue

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#412] opened 2023-05-28 01:29 UTC
### Version

3.0.4 (f015691)

### Seed

R730-R2LC-XXHJ0HCH28F001BNYJ803246CC00RZZZ80Z

### Scenario

RE 1 (Chris)

### Player Character

Leon

### What happened?

Me again
I tried to see if there was any crash with the other Carlos' event
When Carlos (William) appear he had no dialog, so the scene stop there, like waiting to finish his dialog but sincehe had none... nothing happen there
I can skip it anyway, so is not a softlock
Debug save there
[Debug Save.zip](https://github.com/IntelOrca/biorand/files/11583406/Debug.Save.zip)
btw, i hadn't find any other crashes related with the Granade Launcher in this scene

**Comment by baesik** [comment] 2023-05-28 09:17
I can confirm this on my end. Looking at the log I see:

>     210:255 (0x3044) [CARLOS OLIVEIRA 2] becomes [NIKOLAI ZINOVIEV (william)]
>       cutscene #0 contains william, leon
>     211:255 (0x74A8) [CARLOS OLIVEIRA 2] becomes [NIKOLAI ZINOVIEV (william)]
>     211:255 (0x74EC) [CARLOS OLIVEIRA 2] becomes [NIKOLAI ZINOVIEV (william)]
>         DATA_A/VOICE/M211A010.WAV [jill.re3] becomes pl0/voice/stage3/v034.sap [leon]
>         DATA_A/VOICE/M211A020.WAV [jill.re3] becomes pl0/voice/stage1/v014.sap [leon] (0.70-1.65)
>         DATA_A/VOICE/M211A030.WAV [carlos] becomes UCbirkin7.ogg [william] (0.00-2.56)
>         DATA_A/VOICE/M211A040.WAV [carlos] becomes ev7306.ogg [william] (0.00-2.17)
>         DATA_A/VOICE/M211A050.WAV [carlos] becomes ORCBirkin11.ogg [william] (0.00-3.18)

It seems like the game can't find the audio file to play.

**Comment by IntelOrca** [comment] 2023-05-28 21:36
I think I have fixed this now, hopefully also a duplicate of #278

**Closed by IntelOrca** 2023-05-28 21:36 UTC
Labels: RE 3
