### ISSUE TITLE
Blood suckers crashing in rpd

### ISSUE THREAD

**Issue by Smurphy2014** [IntelOrca/biorand#289] opened 2023-03-13 04:11 UTC
### Version

3.0.0 (fafcdd5)

### Seed

R730-50YW-T0ZL0A4Z2Y000MZBJ940ZZZZZZZZZZZZ00Z

### Scenario

RE 3 (Jill)

### What happened?

Shooting bloodsuckers with samurai edge was crashing my game in the hallway of the rpd where nemesis comes through the window.

**Comment by IntelOrca** [comment] 2023-03-16 21:59
Duplicate of #286

**Closed by IntelOrca** 2023-03-16 21:59 UTC
Labels: RE 3
