### ISSUE TITLE
Lab 40a Visual Bug

### ISSUE THREAD

**Issue by gman019** [IntelOrca/biorand#410] opened 2023-05-28 00:18 UTC
### Version

3.0.4 (f015691)

### Seed

R730-NP4W-ZJC888W09Y000149K4T3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Kendo (RE2)

### What happened?

Entered the lab from the factory save room with the magnum equipped. Seemed to have a missing background when I entered.

![2023-05-28 01-15-50](https://github.com/IntelOrca/biorand/assets/127728761/dcfb4ded-9c3e-4673-967a-e881a5fc8716)

**Comment by baesik** [comment] 2023-05-28 08:51
I believe this is a duplicate of #398. Change the player character to something other than OG Kendo for a work-around this issue.

Debug save attached for easy testing.
[01_2023-05-28 01^50.49.zip](https://github.com/IntelOrca/biorand/files/11584109/01_2023-05-28.01.50.49.zip)

**Closed** 2023-05-28 09:14 UTC
