### ISSUE TITLE
problem in piano room

### ISSUE THREAD

**Issue by jodafro619** [IntelOrca/biorand#844] opened 2024-02-23 01:46 UTC
### Version

3.2.6 (8171900)

### Seed

R710-FLJE-XXHH40ZZZMEZ9H00H1NVPEVPEV4ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

rebecca

### What happened?

i picked up an ink ribbon where the music sheets were and then the wall closes and i was stuck looking at the view inside where the plaque for the puzzle goes to

**Comment by IntelOrca** [comment] 2024-02-23 02:12
Duplicate of  #790

**Closed by IntelOrca** 2024-02-23 02:12 UTC
