### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by kattoleen** [IntelOrca/biorand#476] opened 2023-07-03 03:20 UTC
### Version

3.0.8 (a1e8985)

### Seed

R710-0000-ZTHEA0CF9Y020N2TEL69ZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Claire

### What happened?

I just booted Bio 1, went into a new game with Jill's scenario and the black screen with "they have escaped into the mansion..." appeared before crashing. Didn't even get to see the first cutscene.

**Comment by otamega72** [comment] 2023-07-03 14:25
Some playable skins might crashed the game.  : claire , leon , leon.re2r , regina , rebecca , enrico , wesker , richard.
I wonder why Rebecca skin also crashed too.
I copied  jpn\enemy\CHAR13.EMD to replace biorand\data\re1\pld1\rebecca\CHAR11.EMD , then Rebecca skin work fine.

**Comment by kattoleen** [comment] 2023-07-03 16:06
Nice!! it worked, thank you so much :)

**Comment by otamega72** [comment] 2023-07-03 16:14
Here's the problem. 
![re1 character](https://github.com/IntelOrca/biorand/assets/120957601/b28228e2-3173-40fb-b002-722f1188d8b2)

**Comment by IntelOrca** [comment] 2023-07-03 17:23
The problem is caused by `face.png` being copied to char10. It has been since fixed in dev. builds.

**Closed by IntelOrca** 2023-07-03 17:23 UTC
