### ISSUE TITLE
Fell Down the Sewerhole and got Soft Locked

### ISSUE THREAD

**Issue by WeathermanCan** [IntelOrca/biorand#474] opened 2023-07-02 16:07 UTC
### Version

3.0.8 (a1e8985)

### Seed

R720-0000-ZJHHH0M49Y4P0BLP6JM4VZZZBC9GVVZZZNY

### Scenario

RE 2 (Claire A)

### Player Character

Rebecca

### What happened?

I used the blue keycard on the computer in the main hall. And Unlocked the two doors. I walked into the door on the right-hand side of the main entrance and got the cutscene where the player falls down a drain shaft near the floor. After I fell I was stuck. Couldn't get up and couldn't go forward.

**Comment by Neil-F2** [comment] 2023-07-04 15:14
Well in my case i could move but i couldn't  get out of the room
Anyway, the problem could be that you are Playing Claire A, while the randomizer is set to randomize Leon A/Claire B, this could be the cause of this issue... i think

**Comment by IntelOrca** [comment] 2023-07-04 20:47
Closing as incorrect scenario was played

**Closed by IntelOrca** 2023-07-04 20:47 UTC
