### ISSUE TITLE
Crash in the room with the piano in the Clock Tower

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#339] opened 2023-04-07 01:42 UTC
### Version

3.0.1 (412b94e)

### Seed

R730-RL6G-XXHHCACZ1UJ00NJMXH20KC060J70ZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Nikolai (RE3R)

### What happened?

Hi, i found a crash
When entering the room with the piano in the clock tower the game immediately crash all the time, i hear a Brain Sucker in the room before it crash

**Comment by IntelOrca** [comment] 2023-05-02 23:14
Duplicate of #314

**Closed by IntelOrca** 2023-05-02 23:14 UTC
Labels: RE 3
