### ISSUE TITLE
Bug Sheva and Wesker in Tram

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#223] opened 2023-02-06 03:47 UTC
### Version

2.2.1 (bd54d6c)

### Seed

R620-QF9G-ZTLK4C4VFT1G003R4AKKC1MAKVYZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

![Screenshot_20230205_104526](https://user-images.githubusercontent.com/122331724/216879484-f8f62603-8547-45c4-8a2c-76662b3bbbc1.png)

after this screen froze but could hear wesker getting hit in the background and when I tried to reload the room the debug menu didn't show but it still tried to reload and crashed.

**Comment by IntelOrca** [comment] 2023-02-09 21:47
Duplicate of #241

**Closed by IntelOrca** 2023-02-09 21:47 UTC
