### ISSUE TITLE
Shooting explosive barrel in room 21A causes crash

### ISSUE THREAD

**Issue by ruinedplay** [IntelOrca/biorand#287] opened 2023-03-13 01:05 UTC
### Version

3.0.0 (fafcdd5)

### Seed

R730-1U67-XXPH403Z2PA00N8KW921ZQE5ZYQVZZZZX6Y

### Scenario

RE 3 (Jill)

### What happened?

Game crashed after shooting the explosive barrel in room 21A with 2 dogs next to it. I loaded my save in an unmodded game to make sure it wasn't an issue with my game and it worked fine. It only crashes in Biorand

**Comment by IntelOrca** [comment] 2023-05-02 22:31
Duplicate of #328

**Closed by IntelOrca** 2023-05-02 22:31 UTC
Labels: RE 3
