### ISSUE TITLE
Leon A - Crash After Leaving Cable Car After Birkin Attack

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#208] opened 2023-01-28 17:13 UTC
Version: BioRand 2.1.7
Seed: R520-FX0A-ZTBE9MQLL16Q

Can't tell if it was the room or the enemy that caused the crash. Screen went black once I opened the door.

Thank you so much for making this
 randomizer!

![image](https://user-images.githubusercontent.com/123828971/215279853-08b6bd7d-7aee-49e0-b5e6-8c1ae62861a8.png)

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/10527828/log_pl0.txt)

**Comment by IntelOrca** [comment] 2023-01-28 21:21
This room tended to crash when you the partner and random enemies spawn. This should be fixed in the dev. builds.

**Comment by missingno1711** [comment] 2023-01-29 03:05
Sounds good. Were you keeping issues open until they are fixed in the next release? Or did you want me to close this one?

**Comment by IntelOrca** [comment] 2023-01-29 03:20
Duplicate of #193

**Comment by IntelOrca** [comment] 2023-01-29 03:21
> Sounds good. Were you keeping issues open until they are fixed in the next release? Or did you want me to close this one?

I think it is the same as #193, so I have closed it as duplicate.

**Closed by IntelOrca** 2023-01-29 03:20 UTC
