### ISSUE TITLE
Chimeras potentially causing crashes?

### ISSUE THREAD

**Issue by doubleedger1** [IntelOrca/biorand#79] opened 2022-12-18 14:59 UTC
Hello, I've done two small tests on the randomizer using v 2.0.1 and it seems like whenever you kill a chimera it causes the game to crash.

![image](https://user-images.githubusercontent.com/6100003/208305362-2b64eccd-c482-4ebe-982d-2d968a5d3fec.png)
![image](https://user-images.githubusercontent.com/6100003/208305375-4d0bb173-58f0-40dc-8261-0063f4588ff1.png)

Seed: R410-AEMM-Z1N8AQXL100
I forgot to get the seed for the other one so it's lost but they both crashed after killing chimeras.

**Comment by IntelOrca** [comment] 2022-12-18 15:27
Duplicate of  #70

**Closed by IntelOrca** 2022-12-18 15:27 UTC
