### ISSUE TITLE
Wesker Texture Bug if shot during RE2 Lab Cutscene (Replacing Ada)

### ISSUE THREAD

**Issue by gman019** [IntelOrca/biorand#332] opened 2023-03-22 21:43 UTC
### Version

3.0.1

### Seed

N/A

### Scenario

RE 2 (Leon A)

### Player Character

Billy

### What happened?

Forgotten seed number, probably occurs in all instances where Wesker replaces Ada. Picture attached. Wesker model looks fine up until the moment he is shot by character replacing Annette.

![image](https://user-images.githubusercontent.com/127728761/227045058-10058327-4daa-425a-aa6c-50b0a7cc3e89.png)

**Comment by IntelOrca** [comment] 2023-05-02 19:33
Duplicate of #269

**Closed by IntelOrca** 2023-05-02 19:33 UTC
Labels: RE 2
