### ISSUE TITLE
Cured

### ISSUE THREAD

**Issue by TheTaxMan92** [IntelOrca/biorand#642] opened 2023-10-27 20:56 UTC
### Version

3.1.6 (0f27194)

### Seed

R730-9FMW-XX54P5M5Z9Y000QNZT82MWZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Alfred

### What happened?

After curing Jill, you go through the double doors in the Clock Tower crashes.

**Comment by IntelOrca** [comment] 2023-11-02 18:27
Are you able to upload a saved game before the crash occurs?

**Comment by IntelOrca** [comment] 2023-11-02 18:28
Duplicate of  #630

**Closed by IntelOrca** 2023-11-02 18:28 UTC
