### ISSUE TITLE
RE2 - Not Able To Use Valve Handle In Room 409

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#624] opened 2023-10-16 01:25 UTC
### Version

3.1.5 (aac76e0)

### Seed

R720-RGNT-ZXHHH0G7W9Y000ZJ00W00000VXZGQTGZXZGZZ10W100ZZ

### Scenario

RE 2 (Leon A)

### Player Character

Ben

### What happened?

In the Bridge 2F area, I can't pass through the vent without using the valve handle to slow the fan down. 
![image](https://github.com/IntelOrca/biorand/assets/123828971/156e8175-2074-48fe-88db-37f30f7febd3)
![image](https://github.com/IntelOrca/biorand/assets/123828971/85626e6b-c543-4770-936f-077598584135)

**Comment by missingno1711** [comment] 2023-10-16 01:26
Just realized this has been already reported.

**Comment by IntelOrca** [comment] 2023-10-16 20:22
Duplicate of #621

**Closed by IntelOrca** 2023-10-16 20:22 UTC
