### ISSUE TITLE
Resident Evil 2  looping animation.

### ISSUE THREAD

**Issue by LunaHang** [IntelOrca/biorand#576] opened 2023-09-10 21:17 UTC
### Version

3.1.3 (cbe02d7)

### Seed

R720-UBN1-XMHH40MZ9Y1R0NJVPEVPEZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Alfred

### What happened?

When being grabbed by a zombie arm, Leon (Ada) shot and the character was in a loop, I couldn't get out unless I closed the game.

This happened in the Leon A -  Room 502 underg. passage

**Comment by IntelOrca** [comment] 2023-09-11 17:24
Duplicate of #254

**Closed by IntelOrca** 2023-09-11 17:24 UTC
