### ISSUE TITLE
3.0.2 RE3 20c 302 bug

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#382] opened 2023-05-23 15:12 UTC
### Version

3.0.2

### Seed

R730-07PC-ZTC885XZ3Z300NRPW4T0VZZQGYZZVZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Annette  

### What happened?

generator : R730-07PC-ZTC885XZ3Z300NRPW4T0VZZQGYZZVZZZZZZ
pl0.txt : R730-07PC-ZTC885XZ3Z320NRPW4T0VZZQGYZZZZZZZZZ

1. jill , carlos and nikolai in cable car cut scene crashed
disable mod_biorand\room and \data_a also cannot avoid crashing
[c 20c_2023-05-23 20^50.17.zip](https://github.com/IntelOrca/biorand/files/11545534/c.20c_2023-05-23.20.50.17.zip)

2. 302 backgroup music lag
[c 302 03_2023-05-23 20^35.24.zip](https://github.com/IntelOrca/biorand/files/11545561/c.302.03_2023-05-23.20.35.24.zip)

3. NPC and voice did not match ( npc jill , chris voice)
20c insert all 3 items in cable car to trigger carlos cut scene.  
[c voice 05_2023-05-23 21^31.43.zip](https://github.com/IntelOrca/biorand/files/11545593/c.voice.05_2023-05-23.21.31.43.zip)

**Comment by IntelOrca** [comment] 2023-05-23 22:17
I think 3. is a duplicate of #378

**Comment by IntelOrca** [comment] 2023-05-23 22:21
2. I am not sure what you mean by "backgroup music lag"

**Comment by otamega72** [comment] 2023-05-24 00:11
> 2. I am not sure what you mean by "backgroup music lag"

audio glitching

**Comment by IntelOrca** [comment] 2023-05-24 00:14
@otamega72 hmm, I didn't notice any audio glitching when I tried it

**Comment by otamega72** [comment] 2023-05-24 00:17
> @otamega72 hmm, I didn't notice any audio glitching when I tried it
Then I think it might be my pc problem. 
![Capture](https://github.com/IntelOrca/biorand/assets/120957601/d2b7ced0-e362-46fc-b5bf-57cacbfcbec4)

**Comment by IntelOrca** [comment] 2023-05-24 00:20
Possibly, but I think it is worth trying the same version of the game I have. Send me a message on discord, link to channel is on the biorand UI.

**Closed** 2023-06-18 21:08 UTC
Labels: bug, RE 3
