### ISSUE TITLE
Softlock at the dust shoot

### ISSUE THREAD

**Issue by dontjoome** [IntelOrca/biorand#65] opened 2022-12-15 19:32 UTC
Seed: R320-XV0Y-V1HHHMZ

It asked me if I wanted to go down the dust shoot after grabbing the item, but then it said I unlocked it and I was softlocked, I don't know how feasible it would be to make sure that one instance doesn't happen.

Will be turning on debug mode after this one, and hate to post another one so quickly 

That being said I'm really enjoying these :D

**Comment by IntelOrca** [comment] 2022-12-15 21:53
Duplicate of #61

**Closed by IntelOrca** 2022-12-15 21:53 UTC
