### ISSUE TITLE
RE3 Crashes after the girl is killed outside warehouse

### ISSUE THREAD

**Issue by imvr17** [IntelOrca/biorand#344] opened 2023-04-15 20:21 UTC
After meeting "Brad" at the bar and having picked up all items so far, I went back to the first save room, saved, and when I try to leave the warehouse the game crashes after the door closes. There were 2 dogs there that I killed before entering the warehouse.

Seed: R730-RE4K-XXAKCJKZ9Y900N8KJBT0H215K0H2JZZZZZZ

UPDATE: I generated another seed (R730-HH4M-XEZZXZK02FK00MRMZCX0001JH0H2QZZZ0RZ) and the problem persists

**Comment by IntelOrca** [comment] 2023-05-02 22:50
Duplicate of #346

**Closed by IntelOrca** 2023-05-02 22:50 UTC
Labels: RE 3
