### ISSUE TITLE
JaguarStoneL 

### ISSUE THREAD

**Issue by Snipzu** [IntelOrca/biorand#196] opened 2023-01-23 07:58 UTC
Version: BioRand 2.1.7
Seed: R520-B65Z-ZTMR0F4HL55B

JaguarStoneL x1 is in the Dark room as developed Film A, Film A doesnt spawn at all.

Also Film isnt supposed to be key items.

**Comment by Snipzu** [comment] 2023-01-23 07:58
Claire B

**Comment by IntelOrca** [comment] 2023-01-26 23:10
Duplicate of #200

**Closed by IntelOrca** 2023-01-26 23:10 UTC
Labels: bug
