### ISSUE TITLE
RE2, 102 Roji, Arms cause character to get stuck

### ISSUE THREAD

**Issue by STARSMember930** [IntelOrca/biorand#774] opened 2024-01-05 15:12 UTC
### Version

3.2.1 (0770993)

### Seed

R720-8L35-XXHH20L5Z9YBRH7TZZZZZZZ5ZZZZZZZZZZZZZZZZZZZJZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Jill

### What happened?

When entering the basketball area, if the playable character is grabbed by arms AND the character following you shoots at them, you will be stuck in the struggling animation. This can be worked around via debug by jumping back to the start of the room OR by avoiding the arms. Attaching save file at that area, just walk forward. 
[Leon A_00_2024-01-05 10^06.40.zip](https://github.com/IntelOrca/biorand/files/13843607/Leon.A_00_2024-01-05.10.06.40.zip)

**Comment by IntelOrca** [comment] 2024-01-06 10:59
Duplicate of #736

**Comment by IntelOrca** [comment] 2024-01-06 11:00
Thanks, will download your saved game

**Closed by IntelOrca** 2024-01-06 10:59 UTC
