### ISSUE TITLE
RE 2, room 60C, crash possibly due to moths

### ISSUE THREAD

**Issue by TheOnyx1** [IntelOrca/biorand#257] opened 2023-02-18 21:15 UTC
### Version

2.2.2 (81c73fc)

### Seed

R621-U8RR-XZHHHBZ9FT5Q4BQX2Z00000000YZ0HZ

### Scenario

RE 2 (Claire A)

### What happened?

I am experiencing weird crashes/softlocks using this seed. 
1st crash (minor) : First time it happened when I used the Underground Gondola & I made it across to the other side with sherry (I was on Claire A). After getting off the gondola there were a ton of moths everywhere and if you go to the area near that mortar cannon that you need to use the lighter on to see a item  on the ground. The game would crash and it is not possible to get the item (it sort of disappeared / unobtainable).  I was able to get past this crash by running into the next room.

2nd crash (Major / Gamebreaking Bug) : I just defeated Birkin on the train leading down to the laboratory and I did the cutscene with Sherry in the safe room. In the safe room I obtained the main fuse for room **608 Main Shaft**. I went into the room and notice d that Sherry was still following me and I put the main fuse in to power up the laboratory. I went into room **60C Right Passage** and encountered moths everywhere and it always crashes preventing me from finishing the game. If I try to open that door next to the shutters it crashes, if I try to kill the months it will still crash.

Down below is footage of the lab crash.

https://user-images.githubusercontent.com/115422179/219899756-d5bc0e06-4ce6-4025-9bd5-eef502f4f4ff.mp4

**Comment by IntelOrca** [comment] 2023-03-04 22:52
The first issue is #251, and is now fixed.

Unfortunately, I was not able to reproduce the second issue. So I do not know whether the problem was caused by moths specifically or whether it can happen with any enemy type.

**Closed** 2023-05-02 20:08 UTC
Labels: bug, RE 2
