### ISSUE TITLE
RE 3, room 20F, Marvin turned into zombie and can't be killed

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#321] opened 2023-03-19 04:40 UTC
### Version

3.0.0

### Seed

R730-CKVE-ZTFGHGNZ3ZG00N8K8K40ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Nikolai (RE3R) 

### What happened?

Marvin turned into zombie and can't be killed after nemesis entering press office. Nemesis was busy to beat Marvin and ignored PC. 
(This is quiet funny , you can consider this a challenge rather than a bug)
[20f 03_2023-03-17 00^11.53.zip](https://github.com/IntelOrca/biorand/files/11010239/20f.03_2023-03-17.00.11.53.zip)

**Comment by IntelOrca** [comment] 2023-05-04 22:20
Kind of a duplicate of #336, or rather the issue was that Carlos became Marvin which doesn't work well in this room. This is now fixed.

**Closed by IntelOrca** 2023-05-04 22:20 UTC
Labels: RE 3
