### ISSUE TITLE
Resident evil 2 

### ISSUE THREAD

**Issue by magicalcraig** [IntelOrca/biorand#788] opened 2024-01-15 19:09 UTC
### Version

3.2.3 (5e89e20)

### Seed

R721-LGFM-ZNHHJ0M5Y9Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

jill

### What happened?

after you blow up that door where the helicopter blocking and when you go through that door it will lead you to a long cutscene but when the cutscene happens you are getting attack by 4 nemmys and you can't do nothing so you end up died and i check if there's any other way round it and there isn't

**Comment by IntelOrca** [comment] 2024-01-22 00:05
Duplicate of #800

**Closed by IntelOrca** 2024-01-22 00:05 UTC
