### ISSUE TITLE
Knife-Beretta randomly appearing in the inventory.

### ISSUE THREAD

**Issue by silberberg44** [IntelOrca/biorand#567] opened 2023-09-06 20:09 UTC
### Version

3.1.2 (5a4a08a)

### Seed

R710-3NX4-V8HHH0GZ9Y000F5ZZZZZZZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Chris

### What happened?

Max Inventory Size enabled. When I use an item or combining herbs in the inventory, a usable Beretta with a knife icon (with number 15, signifying the number of bullets in Beretta) spawns. But when I perform another action, the knife icon turns back into Beretta.

![image](https://github.com/IntelOrca/biorand/assets/21288699/ebd30557-d06a-4161-b7c9-6c69efb97a7c)
![image](https://github.com/IntelOrca/biorand/assets/21288699/f646cc61-33bc-408d-8539-27e09daaaf1b)

Ways of reproduction: try to pick up the EMBLEM in the DINING ROOM and then put it back. To turn the KNIFE-BERETTA icon back to BERETTA icon, simply pick up the same EMBLEM. 

Log file: [log_pl0.txt](https://github.com/IntelOrca/biorand/files/12542072/log_pl0.txt)
The client used from the game + randomizer pack.

UPD: Tried generating the seed with Max Inventory Size disabled - the issue doesn't occur, which means the issue lies within that particular setting.

**Comment by IntelOrca** [comment] 2023-09-06 21:04
Duplicate of #565

**Closed by IntelOrca** 2023-09-06 21:04 UTC
