### ISSUE TITLE
Graphical glitches preceeding replicatable hard crash

### ISSUE THREAD

**Issue by Garebear94** [IntelOrca/biorand#347] opened 2023-04-30 16:29 UTC
### Version

v3.0.1

### Seed

R730-8Z40-XJQLCPGZ4Z900EV2EL60ZZZZZQZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Upon entering the trolley control room for the first time (room 20c) a cutscene plays that causes the player model to load in as a strangely textured vaguely masculine model. When the scene ends the graphics for the player model and all menus remain bugged but other characters in the following scene are fine.
Aside from the graphical glitches. Upon entering the clock tower from the courtyard after the "use emergency break" event the game hard crashes to desktop. I have been able to replicate this crash multiple times and cannot proceed past it.
Choosing the jump out the window option allows the game to continue with the same graphical glitches until you enter room 301 at which point the had crash occurs again. 

![Screenshot (1)](https://user-images.githubusercontent.com/132217505/235364159-b0ec590a-7b70-45ba-b879-16485d51f602.png)
![Screenshot (2)](https://user-images.githubusercontent.com/132217505/235364161-70a12a5f-c74e-463a-b995-fa5d042c999d.png)
![Screenshot (3)](https://user-images.githubusercontent.com/132217505/235364162-3c470571-6d89-4514-87d8-fbe4952504f5.png)

**Comment by IntelOrca** [comment] 2023-05-20 14:30
Closing, most likely a duplicate of #352

**Closed by IntelOrca** 2023-05-20 14:30 UTC
Labels: RE 3
