### ISSUE TITLE
RE2 - Screen freezes completely upon entering tram car preventing the seed from being completed

### ISSUE THREAD

**Issue by YoshiChief** [IntelOrca/biorand#248] opened 2023-02-09 22:54 UTC
Version - 2.2.1
Seed - R623-YPJ1-ZTHH5C93FT5GZZZZZZZZZZZZZZZZZZZ
Scenario - Claire B

When nearing the end of the B scenario seed, enterting the tram causes the screen to completely freeze until closing the game and restarting. Note the game doesn't crash, you can still move your character, but you can't see where you are going. Even when starting the tram, the FMV scene that normally plays will not play.

![image](https://user-images.githubusercontent.com/123690237/217957239-d6792872-46e8-471e-b442-a39801c3b60d.png)

Note Sheva seems to have no head and arms here.

**Comment by IntelOrca** [comment] 2023-02-09 23:47
Duplicate of #246

**Closed by IntelOrca** 2023-02-09 23:47 UTC
