### ISSUE TITLE
Sheva is mostly not visible :D

### ISSUE THREAD

**Issue by heymert8657** [IntelOrca/biorand#582] opened 2023-09-12 15:51 UTC
### Version

3.1.3 (cbe02d7)

### Seed

R730-9XRX-XX0J4QNZ9YJ10LNJ4U3XXZ1PYGPZTQVZZXZZ0RYZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Sheva

### What happened?

I started a game choosing Sheva. Just letting you know
![Bild_2023-09-12_175107712](https://github.com/IntelOrca/biorand/assets/117825073/7423d3ce-1436-4487-b3fc-08ae2a5a4c99)

**Comment by IntelOrca** [comment] 2023-09-12 23:40
Duplicate of #541

**Closed by IntelOrca** 2023-09-12 23:40 UTC
