### ISSUE TITLE
Crash on the statue room after leaving the Hospital

### ISSUE THREAD

**Issue by Lirte** [IntelOrca/biorand#612] opened 2023-10-07 22:16 UTC
### Version

v.3.1.3

### Seed

R730-5WCW-XXMM4RMZ2ZJ00L182XU2WZ10H801K0M703YZ60YZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Chris (CV), Jill (RE 1)

### What happened?

Was playing the game without any issues (aside from some missing limbs or similar bugs on some character models), but after almost finishing Carlos's segment, the game crashed after I entered the big bell room, with the clock puzzle. Was playing Chris (CV) on Jill's place and Jill with her S.T.A.R.S. outfit instead of Carlos. Don't know, maybe the crash ocurred because of the celling cutscene that plays after Carlos get back to the Clock Tower, since I was playing Jill...don't know

Hope u find the source of the problem. Also thanks for fixing Rebecca's inventory crash, I tested and it worked fine. I appreciate your hard work :)

**Comment by IntelOrca** [comment] 2023-10-09 17:36
Hopefully a duplicate of #598 which has been fixed

**Closed** 2023-10-16 22:14 UTC
