### ISSUE TITLE
Became invisible Sherry

### ISSUE THREAD

**Issue by THH2929** [IntelOrca/biorand#13] opened 2022-11-19 22:15 UTC
Seed: R121-KVV2-Z1Y6BNC

Playing Claire A.  Went into the hall off Chief Irons' office, the one with the tiger taxidermy.  At end of hall was a save room.  When I came back out my status had changed to Sherry and I was completely invisible, could not leave the room.  Had to reset.

**Comment by IntelOrca** [comment] 2022-11-19 22:29
Hi @THH2929, was the save room 30D (east basement, tiny save room) by any chance? If so I think it is the same issue as https://github.com/IntelOrca/biorand/issues/11

**Comment by IntelOrca** [comment] 2022-11-20 02:22
Duplicate of #11 which has now been fixed.

**Closed by IntelOrca** 2022-11-20 02:22 UTC
