### ISSUE TITLE
RE2 Game Breaking Bug  (401 South Office)

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#144] opened 2023-01-12 13:05 UTC
Seed: R520-EV1L-ZTZ93LZLL141

I Opened The Door With A Small Key And Went Down The Ladder In The Room 401 South Office.(Photo 1)

 I Was Taken To The Correct Room But The Game For Some Reason Loads The Mini Platform/Elevator And It's Animation Of Going Up. I Am Completely Out Of Bounds And Off Camera. (Photo 2) Look At Top Upper Middle Right And You Will See The Bottom Of The Elevator Which Does Not Even Belong In This Room At All. It Even Goes Up And Off Camera.

The Licker Is Able To Hurt Me Even Though I'm Far From It. My Hit Box Is Magically Always Immediately In Front Of The Licker, No Matter Where It Is.The Licker's AI Recognizes The Actual Location Of My Character Being Out Of Bounds, And Attempts To Crawl To Me Constantly Moving Into The Wall That Is Below My Character And Attacks It. I Am Unable To Hurt It Being Out Of Bounds Even With The Auto Aim.  (Photo 3)

The Game Does Not Even Know What Room Im Even In And Thinks I'm Still In 401 South Office. Confirmed By The Debug Menu. (Photo 4) Which Is Probably Why It Loads The Elevator.

There Is Absolutely No Possible Way To Get In Bounds Or Go Back By Regular Means. The Debug Menu Is The Only Way To Go Back And Repeat Attempts To Go Down The Ladder Just Repeats The Same Issue.

![1](https://user-images.githubusercontent.com/122418252/212070379-c5493f26-2f89-457c-b2c0-e3c1c3c04278.PNG)
![2](https://user-images.githubusercontent.com/122418252/212070408-5f7eff6e-a1df-4046-ab5e-914e4432a4d7.PNG)
![3](https://user-images.githubusercontent.com/122418252/212070416-71564398-b2e9-484f-8801-0e067b76cb2e.PNG)
![4](https://user-images.githubusercontent.com/122418252/212070421-ee9e4186-edf6-440f-a9cb-5ddec15e858b.PNG)

**Comment by IntelOrca** [comment] 2023-01-12 17:56
Duplicate of #97

**Closed by IntelOrca** 2023-01-12 17:56 UTC
