### ISSUE TITLE
v2.2.1 RE2 Leon A 500->501 crash

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#232] opened 2023-02-07 16:48 UTC
### Version

2.2.1

### Seed

R620-3LQB-ZTHKMXZ3BEEZU6F455ZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

Crash : 
Connected 500:0 to 501: (always)
Created 501:0 (0x0) [Tyrant1,0,0,18,0] at (19300,0,-19317)

501:255 (0x138E) [AdaWong1] becomes [83 (regina)]
501:255 (0x13EE) [AdaWong1] becomes [83 (regina)]

**Comment by IntelOrca** [comment] 2023-02-07 23:10
Duplicate of #231

**Closed by IntelOrca** 2023-02-07 23:10 UTC
