### ISSUE TITLE
RE 3 room 11B zombie enemies are off-screen and extremely large

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#401] opened 2023-05-26 18:27 UTC
### Version

3.0.2 (243098e)

### Seed

R730-U5GU-ZTHH0HMZ9W300N09K490ZZZZZZZZZZZZF2Z

### Scenario

RE 3 (Jill)

### Player Character

Annette

### What happened?

A follow up to #400.
There are zombie enemies that are out of bounds, but can grab the player. If grabbed, it will move the player off-screen.

The save posted in the previous issue will demonstrate the issue. For ease, here is the same attached debug save.

[01_2023-05-26 11^17.10.zip](https://github.com/IntelOrca/biorand/files/11578800/01_2023-05-26.11.17.10.zip)

**Comment by IntelOrca** [comment] 2023-05-26 20:05
I am not able to reproduce this one.

**Comment by IntelOrca** [comment] 2023-05-26 21:10
Going to make this as a duplicate of #400. Caused by triggering the 11C cutscene before 11B cutscene.

**Closed by IntelOrca** 2023-05-26 21:10 UTC
Labels: RE 3
