### ISSUE TITLE
Randomize Npc's dont work

### ISSUE THREAD

**Issue by nico8521** [IntelOrca/biorand#414] opened 2023-05-28 10:30 UTC
### Version

3.0.4 (f015691)

### Seed

R730-151L-ZTZR8QC9C8C00NK4XK41HH024L05HZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Kendo

### What happened?

for biorand to work, i don't have to select any npc to randomize. Otherwise it gives an error

**Comment by baesik** [comment] 2023-05-28 11:05
I didn't have an issue generating the seed. What is the error it gives? Can you screen record a small clip?

**Comment by nico8521** [comment] 2023-05-28 11:10
https://github.com/IntelOrca/biorand/assets/134842253/b93611b0-3ea8-4dcf-8fe1-ff41d4c52398



> I didn't have an issue generating the seed. What is the error it gives? Can you screen record a small clip?

**Comment by nico8521** [comment] 2023-05-28 11:11
![image](https://github.com/IntelOrca/biorand/assets/134842253/6f89d4a3-272e-4583-8ded-3a69d5e6303a)

**Comment by IntelOrca** [comment] 2023-05-28 11:12
Can you upload your log file? It will be in the mod_biorand folder. You can also click Jill log.

**Comment by nico8521** [comment] 2023-05-28 12:17
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11584520/log_pl0.txt)

**Comment by IntelOrca** [comment] 2023-05-28 21:38
I am not sure what the issue is, it is potentially an issue with the version of the game you have.

**Comment by nico8521** [comment] 2023-05-29 19:59
I changed the version, now it works, I had crash problems with Steve, when using the objects for the train. I tried different seeds but the same situation happens.

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11593922/log_pl0.txt)

**Closed** 2023-06-18 21:09 UTC
Labels: RE 3
