### ISSUE TITLE
Brenda Rosso always causing a crash & other problems

### ISSUE THREAD

**Issue by Soullesscat** [IntelOrca/biorand#334] opened 2023-03-25 17:49 UTC
### Version

3.0.1 (412b94e)

### Seed

R730-WBL9-XQHHHHCZUYB00NK49H2020808A00RZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Jill(RE3R)

### What happened?

When you run after Dario Rosso's daughter she is supposed to be eaten by a zombie but if you do it too soon - my guess is before you encounter Nemesis - then perhaps too many enemies will spawn in the alley preventing her game model to appear properly. I assume she is pushed out of bounds or randomized because she looks like a standard female zombie. Although her model will not be visible and is only represented by a shadow she will cause a crash when you return to the alley that leads to the warehouse. This is a universal bug that appears in every seed. 

![2023-03-25 18-26-18](https://user-images.githubusercontent.com/36854965/227733282-5d9aa320-a769-46b9-852c-dddee572c4a1.png)

**Comment by Soullesscat** [comment] 2023-03-25 18:22
Brenda Rosso will not crash your game if you chase her much later. She will then as always be eaten by an unrandomized zombie and her model should appear properly. I guess there are certain criteria in the backgrounds that indicate if you've done it correctly like the time of day. For example if you leave the police precinct it gets darker outside. However there is another bug. When you leave the station it gets dark but sometimes if you re-enter the police station it will be bright again and Nemesis will still be waiting to fight you as if you never entered the station.

**Comment by Soullesscat** [comment] 2023-03-26 16:31
I figured out how to activate the debug stats in-game so there wasn't a problem with an inaccessible item in this seed however the other bugs are still present.

**Comment by Soullesscat** [comment] 2023-03-26 17:53
Regarding the same seed after shooting a few enemies in room 209 re-entering the room will cause a crash if you enter it again from room 208. I assume this has something to do with how many enemies occupy this room and if they go out of bounds or are only represented by a shadow without a visible player model once the game tries to put them back in place.

![2023-03-26 19-31-38](https://user-images.githubusercontent.com/36854965/227794029-63e9c45f-b83a-444b-bca0-9b7cb6555693.png)

Here's the save file
[savedata.zip](https://github.com/IntelOrca/biorand/files/11072483/savedata.zip)

Also this door can never get opened due to enemy randomization and the missing zombies who push the door open unless Nemesis enters trough the door in the picture above after the gas station blows up. Then the door will be counted as unlocked.

![2023-03-26 19-31-20](https://user-images.githubusercontent.com/36854965/227794487-ea1667ad-8b04-4d44-86f3-3bd2bba1e977.png)

**Comment by Soullesscat** [comment] 2023-03-26 18:41
I have the feeling that rooms where enemies require to do an event because it's scripted like that like zombies bursting out of cars or just require to lie still like Brando Rosso and pretend not to attack the player because they are dead but need to be loaded in-game and are missing due to randomization cause the game to crash. For example room 209 has a different enemy behind a car although there should be a zombie who is then missing which causes an error. So maybe certain enemies and NPCs shouldn't be randomized so that things like these won't happen:

![2023-03-26 20-32-21](https://user-images.githubusercontent.com/36854965/227796891-bb9a3775-878f-414e-9e05-b0898de80538.png)

**Comment by IntelOrca** [comment] 2023-05-02 23:18
The first issue you reported is in room 102. This is a duplicate of #346 which is now fixed.
Could you please raise a separate issue for each bug.

**Closed by IntelOrca** 2023-05-02 23:18 UTC
Labels: RE 3
