### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by ResidentEvil3Randoruns** [IntelOrca/biorand#453] opened 2023-06-21 07:14 UTC
### Version

3.0.7 (0c5a5f2)

### Seed

R730-6WE2-XJZ9207Z9Y100E09W080000200000WZZH1Z

### Scenario

RE 1 (Chris)

### Player Character

Hunk

### What happened?

It is the second time that happens but the game crashes after the hospital in the area where the sliding worms show up, you know? the area with the 3 stones /clock puzzle?
When you pass there after the hospital the game just crashes

**Comment by IntelOrca** [comment] 2023-06-23 21:38
Are you able to provide a debug save before it crashes?

**Comment by ResidentEvil3Randoruns** [comment] 2023-06-25 15:53
Hello.
Oh. I’m sorry, i’ve already deleted that run.
I shall keep the save from now on.
And i will keep the save in case something happens.

My youtube channel is mainly focused in Resident evil 3 Randomizer.
I believe i will be able to provide some good data
If there is anything i can help please tell me.

Best regards
Wish you a good day.

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ted ***@***.***>
Enviado: 23 June 2023 22:38
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [IntelOrca/biorand] Report (Issue #453)


Are you able to provide a debug save before it crashes?

**Comment by Neil-F2** [comment] 2023-07-04 18:47
Well i made it with a save but i couldn't reproduce the crash
But i found another Crash
But i am gonna talk about that in another issue
Here is the save, anyway
[SaveData.zip](https://github.com/IntelOrca/biorand/files/11951813/SaveData.zip)

**Comment by IntelOrca** [comment] 2023-07-04 21:24
I think #472 is the same issue, and that is now fixed.

**Closed** 2023-07-04 21:23 UTC
Labels: RE 3
