### ISSUE TITLE
RE3: Crash when using Rusty Crank

### ISSUE THREAD

**Issue by TheMitu97** [IntelOrca/biorand#444] opened 2023-06-16 20:49 UTC
### Version

3.0.6 (d8709f5)

### Seed

R730-BAXA-ZJHE70VFLPV00V00W000NQNQMPUPPXZZZTZ

### Scenario

RE 3 (Jill)

### Player Character

Regina

### What happened?

This is a problem that seem to happen with recently added characters, for my instance it was both Regina and Hunk. After using rusty crank at Gas Station (room 20E), game immediately crashes. 
Additionally, those new characters seem to have some weird animation issues. When walking or when in caution, they constantly warp back a bit and it's pretty annoying especially in case of caution animation. Save file included, just need to exit through door leading to garage and continue through the main clock tower entrance.
[savefile.zip](https://github.com/IntelOrca/biorand/files/11775800/savefile.zip)

**Comment by IntelOrca** [comment] 2023-06-17 14:46
Duplicate of #443

**Closed by IntelOrca** 2023-06-17 14:46 UTC
