### ISSUE TITLE
Room 301 

### ISSUE THREAD

**Issue by Smurphy2014** [IntelOrca/biorand#316] opened 2023-03-18 05:15 UTC
### Version

3.0.1

### Seed

R731-KX5H-T0ZE06309F0005ZTW940ZZZZZZZZZZZZ00Z     Player: 0 Jill

### Scenario

RE 3 (Jill)

### What happened?

Crashes entering from the dining room 302 room to 301.

**Comment by IntelOrca** [comment] 2023-03-18 13:08
Are you able to provide a same game?

What were had you done so far in the game?

**Comment by Smurphy2014** [comment] 2023-03-18 22:05
Well i was just going to the room nothing in the clock tower was done at the time besides getting into the clock tower section of the game went to the dining area and tried to go to the piano room through the dining area and it just crashed going through the door. everything up to that point in the city was complete that is a just incase info you needed. Was just playing the game all the way through like normal until i got to that point in that seed.

**Comment by IntelOrca** [comment] 2023-05-02 23:22
Duplicate of #314

**Closed by IntelOrca** 2023-05-02 23:22 UTC
Labels: RE 3
