### ISSUE TITLE
Crash at Boss Fight

### ISSUE THREAD

**Issue by sakurayosei** [IntelOrca/biorand#716] opened 2023-12-20 05:19 UTC
### Version

3.1.8 (2f583cd)

### Seed

R721-QMRJ-XNGGG0G5A9Y7N03NZ7XHK206ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Jessica

### What happened?

After the scene with Irons being killed. Tried to go down ladder to fight boss, it crashes. I'm pretty sure this boss fight is the same every time (no randomized enemy) but thought maybe its an enemy skin?
[Sakura_Yosei-jessicabosscrash.zip](https://github.com/IntelOrca/biorand/files/13723274/Sakura_Yosei-jessicabosscrash.zip)

**Comment by IntelOrca** [comment] 2023-12-29 02:11
Duplicate of  #711

**Closed by IntelOrca** 2023-12-29 02:11 UTC
