### ISSUE TITLE
Zombie Hands Stuck

### ISSUE THREAD

**Issue by TronPolan** [IntelOrca/biorand#779] opened 2024-01-07 15:27 UTC
### Version

3.2.1(0770993)

### Seed

R720-ZAV0-ZXHH40M5FCY00H7TZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Annette(RE2R)

### What happened?

A back alley in front of Kendo's gun store.
Annette was caught in her zombie arms and her partner "Leon(RE2R)" rescued her, but Annette was stuck in the captured motion.
No freezes.

**Comment by IntelOrca** [comment] 2024-01-08 21:27
duplicate of #736

**Closed by IntelOrca** 2024-01-08 21:27 UTC
