### ISSUE TITLE
RE3 - Room 402 cutscene freezes the game

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#562] opened 2023-08-31 14:08 UTC
### Version

3.1.1 (1e8850a)

### Seed

R730-B3KX-ZXHM0HXZ9Y000ZJZZZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Annette RE2 Remake

### What happened?

Reached room 402 (Hospital Entrance). Zombie cutscene played out, he was killed by an invisible enemy, and then freeze. Music still plays, but the cutscene wont finish.
![image](https://github.com/IntelOrca/biorand/assets/123828971/37e5642d-a326-4d00-af54-45dd90e3c8e8)

**Comment by IntelOrca** [comment] 2023-08-31 21:09
Duplicate of #550

**Closed by IntelOrca** 2023-08-31 21:09 UTC
